"""new

Revision ID: c2424f2859c7
Revises: c3bae3b7743d
Create Date: 2024-06-15 00:12:15.084784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2424f2859c7'
down_revision = 'c3bae3b7743d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('event_description')
        batch_op.drop_index('event_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('event_location', ['event_location'], unique=True)
        batch_op.create_index('event_description', ['event_description'], unique=True)

    # ### end Alembic commands ###
